### ISSUE TITLE
NullPointer encountered when adding to a Lambda which listens on s3 events

### ISSUE THREAD

**Issue by bajalnyt** [DataDog/datadog-lambda-java#41]
I'm attempting to instrument a Java Lambda as instructed [here](https://docs.datadoghq.com/serverless/installation/java/?tab=gradle#monitor-custom-business-logic). 

On a Java Lambda initialized so:
```
public class MyLambda implements RequestHandler<S3EventNotification, String> {

    @Override
    public String handleRequest(S3EventNotification eventNotification, Context context) {
        DDLambda ddl = new DDLambda(context);
```

```
2021-05-06T11:40:00.384-04:00	java.lang.NullPointerException
2021-05-06T11:40:00.384-04:00	at io.opentracing.propagation.TextMapExtractAdapter.iterator(TextMapExtractAdapter.java:38)
2021-05-06T11:40:00.384-04:00	at datadog.trace.bootstrap.instrumentation.api.ContextVisitors$EntrySetContextVisitor.forEachKey(ContextVisitors.java:55)
2021-05-06T11:40:00.384-04:00	at datadog.trace.bootstrap.instrumentation.api.ContextVisitors$EntrySetContextVisitor.forEachKey(ContextVisitors.java:49)
2021-05-06T11:40:00.384-04:00	at datadog.trace.agent.core.propagation.TagContextExtractor.extract(TagContextExtractor.java:27)
2021-05-06T11:40:00.384-04:00	at datadog.trace.agent.core.propagation.HttpCodec$CompoundExtractor.extract(HttpCodec.java:102)
2021-05-06T11:40:00.384-04:00	at datadog.trace.agent.core.CoreTracer.extract(CoreTracer.java:535)
2021-05-06T11:40:00.384-04:00	at datadog.trace.instrumentation.opentracing32.OTTracer.extract(OTTracer.java:70)
2021-05-06T11:40:00.384-04:00	at io.opentracing.util.GlobalTracer.extract(GlobalTracer.java:204)
2021-05-06T11:40:00.384-04:00	at com.datadoghq.datadog_lambda_java.DDLambda.startSpan(DDLambda.java:138)
2021-05-06T11:40:00.384-04:00	at com.datadoghq.datadog_lambda_java.DDLambda.<init>(DDLambda.java:52)
2021-05-06T12:22:34.202-04:00 | at com.bajal.MyLambda.handleRequest(MyLambda.java:12)
```

Questions:
* What is the best way to initialize DDLambda in this case, where I do not have access to a request object of type `APIGatewayV2ProxyResponseEvent` ?
* If initializing DDLambda with just context does not work, should that constructor be public?

**Comment by agocs** [comment]
Hi @bajalnyt, what version of datadog-lambda-java are you using? This is a known issue in datadog-lambda-java:0.2.1 and below. It should be fixed in 0.2.2 and greater.

**Comment by bajalnyt** [comment]
Thank you for the quick reply @agocs . 
It works fine now with `0.2.3`. I was on `0.0.10`.

**Comment by agocs** [comment]
Ah! That explains it. I think that bug was introduced in 0.0.10. Sorry about that!
