### ISSUE TITLE
dd-trace error when next gen extension is turned on for lambda

### ISSUE THREAD

**Issue by hoangnd25** [DataDog/datadog-lambda-java#94]
I've encountered this error when turning on next gen extension. 
I think maybe java layer needs update?

```
RESTORE_START Runtime Version: java:21.v27	Runtime Version ARN: arn:aws:lambda:ap-southeast-2::runtime:1fe198c3259fb2d78c1f0033293d1f68b2d4a528b2288b3a3fd80a5b6089872f
[dd.trace 2024-12-24 00:38:20:056 +0000] [dd-trace-processor] WARN datadog.trace.agent.common.writer.ddagent.DDAgentApi - Error while sending 1 (size=938B) traces. Total: 1, Received: 1, Sent: 0, Failed: 1. java.net.ConnectException: Failed to connect to localhost/127.0.0.1:8126 (Will not log warnings for 5 minutes)
RESTORE_REPORT Restore Duration: 1215.50 ms
START RequestId: d5ffdeec-41ed-47e9-b2e5-4dfc25300cc0 Version: 3
[dd.trace 2024-12-24 00:38:20:374 +0000] [main] ERROR datadog.trace.lambda.LambdaHandler - could not reach the extension
[dd.trace 2024-12-24 00:38:21:413 +0000] [main] ERROR datadog.trace.lambda.LambdaHandler - could not reach the extension, not injecting the context
java.net.ConnectException: Failed to connect to /127.0.0.1:8124
at datadog.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:249)
at datadog.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:167)
at datadog.okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
at datadog.okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
at datadog.okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
at datadog.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
at datadog.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at datadog.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at datadog.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
at datadog.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at datadog.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at datadog.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
at datadog.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at datadog.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
at datadog.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at datadog.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at datadog.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
at datadog.okhttp3.RealCall.execute(RealCall.java:93)
at datadog.trace.lambda.LambdaHandler.notifyEndInvocation(LambdaHandler.java:162)
at datadog.trace.agent.core.CoreTracer.notifyExtensionEnd(CoreTracer.java:956)
at com.amazonaws.services.lambda.runtime.api.client.EventHandlerLoader$PojoHandlerAsStreamHandler.handleRequest(EventHandlerLoader.java:670)
at com.amazonaws.services.lambda.runtime.api.client.EventHandlerLoader$2.call(EventHandlerLoader.java:601)
at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:240)
at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:190)
at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.main(AWSLambda.java:180)
"Caused by: java.net.ConnectException: Connection refused
"
"at java.base/sun.nio.ch.Net.pollConnect(Native Method)
"
"at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
"
"at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
"
"at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
"
"at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
"
"at java.base/java.net.Socket.connect(Unknown Source)
"
at datadog.okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
at datadog.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
... 24 more
```

**Comment by purple4reina** [comment]
Hey @hoangnd25, thanks for reaching out. We have tested the java layer for compatibility with our next gen extension with no issue. It looks like from this error that the problem is not the java layer but that your extension isn't starting up properly or somehow becomes unavailable.

Can you share more about your set up?
+ Which java version are you using?
+ Which version of the java layer are you using?
+ Which version of the extension layer are you using?
+ Which, if any, environment variables are you setting?
+ Do you have snap start enabled?
+ What tool are you using for deploys? Can you share a bit of that code?

With that provided, I'm looking forward to helping get to the bottom of this.

**Comment by hghotra** [comment]
Closing this since we haven't heard anything back - please re-open if the issue still persists.
